### ISSUE TITLE
Fixing deprecated code within virtual env

### ISSUE THREAD

**Issue by residentcode** [adamchainz/django-upgrade#116]
### Description

Could you please implement accessing and fixing the deprecated import within the virtual envirement ?
there are some apps still have deprecated import for Django 4.0 I had to update them manually .
Appreciated .

**Comment by adamchainz** [comment]
It's a bad idea to modify code after installing it. It won't be tested in the state after modification, and you should be rebuilding your virtual environments no every deploy to ensure they are clean.

For your third party apps with deprecation warnings, make pull requests to fix them upstream.
