### ISSUE TITLE
Issue with url function replacement

### ISSUE THREAD

**Issue by qdufrois** [adamchainz/django-upgrade#121]
### Python Version

3.7

### Django Version

2.2

### Package Version

1.4.0

### Description

Django-upgrade changes this kind of `url` functions:
```url(r"^foo", my_view)```

with these `path` functions:
```path("foo", my_view)```

However, the automated change made by the library is not backwards compatible. The initial code allowed all paths such as  `foos`, `footest` etc., whereas the upgraded code only allows `foo` (the missing `$` in the first example being the problem).

For this use-case, a backwards compatible solution would have been this:
```re_path(r"^foo", my_view)```

I would be glad to offer any help needed if you would take this issue into consideration.

**Comment by matthiask** [comment]
I'm surprised that `url(r"^/foo", ...)` even matches anything. it doesn't seem to work in my local testing at all.

The Django docs state that there's no need to add a leading slash and I haven't found a single example containing a leading slash. I'm sure it works on your end but it's still strange.

**Comment by qdufrois** [comment]
Yeah my bad, that was not a good example, let's forget about those leading slashes, I have removed them in the example to avoid the confusion.

**Comment by adamchainz** [comment]
Fixed in #133

**Comment by qdufrois** [comment]
Thanks a lot for this :bow:
