### ISSUE TITLE
Migrate django.utils.timezone.utc to datetime.timezone.utc

### ISSUE THREAD

**Issue by carltongibson** [adamchainz/django-upgrade#135]
### Description

Django 4.1 deprecates the `django.utils.timezone.utc` alias to `datetime.timezone.utc`. Folks should use `datetime.timezone.utc` directly. 

https://github.com/django/django/commit/59ab3fd0e9e606d7f0f7ca26609c06ee679ece97

This seems like a good candidate for `django-upgrade`, as @adamchainz [convincingly argued on a recent Django Chat](https://djangochat.com/episodes/boost-your-django-dx-adam-johnon) 🎙😜

**Comment by adamchainz** [comment]
Yup, that would be a fairly straightforward replacement! Thanks for the issue

**Comment by browniebroke** [comment]
Is that something that is "too early" to tackle? As in, should we wait for the first beta/stable release? Looking at the diff, it looks like we could do this replacement even before 4.1, would it make sense to apply it to earlier versions or would you rather stick to Django's deprecation timeline to avoid questions/confusion from users?

**Comment by carltongibson** [comment]
I wouldn't apply it before 4.0, which changed from pytz.

**Comment by adamchainz** [comment]
The policy with django-upgrade is to rewrite on the version that first deprecates a thing. So we'll do version 4.1 here.

Yes it's possible to use `datetime.timezone.utc` earlier, perhaps even before 4.0 for most use cases, but I think it's best we just stick to django's deprecations to reduce surprise.
