### ISSUE TITLE
Rewrite compatible `re_path()` to the new `path()` syntax

### ISSUE THREAD

**Issue by UnknownPlatypus** [adamchainz/django-upgrade#160]
### Description

Hi, 

I came here after discovering [pyupgrade](https://github.com/asottile/pyupgrade), these are fascinating projects, really like it !

I created this issue to suggest a slight improvement of this feature: 
> url() calls using compatible regexes are rewritten to the [new path() syntax](https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax), otherwise they are converted to call re_path()

This is nice and could also be useful to convert compatible `re_path()` to simpler `path()` syntax. 
It would benefit projects that handled the deprecation by simply replacing `url()` calls with `re_path()` calls directly. It's also usually nice to use the path() syntax instead of unnecessary regexes when possible.

I'm working on a PR for this, let me know if it's something you would be interested in.
Cheers

**Comment by adamchainz** [comment]
Yes this is an idea I had after writing the initial converter - see the duplicate issue #60.

Please include docs and changelog in your PR.
