### ISSUE TITLE
Delete `USE_L10N` setting if Django version >= 4.0

### ISSUE THREAD

**Issue by johnnymetz** [adamchainz/django-upgrade#161]
### Description

The `USE_L10N` setting is deprecated in Django 4.0: https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-USE_L10N

Figure this would be a good candidate for this project. Happy to work on it if you agree.

**Comment by adamchainz** [comment]
Yeah we could remove it, but only if it's set to exactly `True`: `USE_L10N = True`.

The `password_reset_timeout_days` fixer rewrites another setting, you can use that for guidance.

Please ensure you test, update docs, and add a changelog note.

**Comment by johnnymetz** [comment]
There are two changes here. According to the settings page: https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-USE_L10N

- Changed in Django 4.0: In older versions, the default value is False.
- Deprecated since version 4.0: This setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.

How should we handle this? I imagine:

- Django 4.x:
  - If `USE_L10N = True`: remove the setting
  - If `USE_L10N = False`: no action
- Django 5.x: 
  - If `USE_L10N = True`: remove the setting
  - If `USE_L10N = False`: not totally sure what to do here. Probably remove it because it has no effect. But I'm slightly worried this may confuse the user. They may think their app's behavior is changing because `django-upgrade` removed the setting when it's in fact due to a library change. But I'm sure the [Fixers docs](https://github.com/adamchainz/django-upgrade#fixers) will clarify this so maybe I shouldn't be so concerned.

Or should we just not worry about Django 5.0 yet because it hasn't been released yet?

**Comment by adamchainz** [comment]
I don't see it as the responsibility of django-upgrade to worry about `USE_L10N = False`. django-upgrade updates files where it's definitely safe to do so.

Django will log a deprecation warning for it from version 4.0. If users ignore that all the way through to version 5.0, that's on them. At that point, leaving the single line in their settings file is going to be the least of their problems, and may even help them debug localization problems.

**Comment by johnnymetz** [comment]
Sounds great! Just put up the initial PR. I left `USE_L10N = False` alone.
