### ISSUE TITLE
Extensions to `@admin.register` fixer

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#190]
### Description

Following #182 / #189 , there are a few more cases that could be covered with further work.

1. Support kwarg form ✅ #192

```diff
+@admin.register(MyModel)
 class MyModelAdmin(...):
    ...

-admin.site.register(MyModel, admin_class=MyModelAdmin)
```

2. Support multiple models ✅ #200

```diff
+@admin.register(Model1, Model2)
 class MyModelAdmin(...):
    ...

-admin.site.register(Model1, MyModelAdmin)
-admin.site.register(Model2, MyModelAdmin)
```

```diff
+@admin.register(Model1, Model2)
 class MyModelAdmin(...):
    ...

-admin.site.register((Model1, Model2), MyModelAdmin)
```

3. Support when there are other class decorators, insert at top ✅ #193

```diff
+@admin.register(MyModel)
 @something
 class MyModelAdmin(...):
    ...

-admin.site.register(MyModel, MyModelAdmin)
```

4. Support custom admin sites ✅ #228

```diff
from myapp.admin import custom_site

+@admin.register(MyModel, site=custom_site)
 class MyModelAdmin(...):
    ...

-custom_site.register(MyModel, MyModelAdmin)
```

- detect custom site objects heuristically, to avoid affecting other code that uses a 'register' pattern, perhaps when the object's name ends in 'site', and the registered class name ends in 'Admin' (and maybe the file looks like an admin file, called "admin.py" or in an "admin" directory?)

5. Also work for `from django.contrib.gis import admin` - ✅ #204 
   This imports the `register` decorator for convenience when authoring GIS apps.

**Comment by adamchainz** [comment]
@UnknownPlatypus I have entertained myself tackling the two easiest ones here, perhaps you'd like to try the other two?

**Comment by UnknownPlatypus** [comment]
@adamchainz Absolutely, would be nice to work on that and I think I have some ideas on how to tackle them.

**Comment by adamchainz** [comment]
@UnknownPlatypus added point 5 above as well, for GIS admins.

**Comment by adamchainz** [comment]
Alright we've checked everything off from this list! 🥳

This is now a really awesome feature that covers many cases. Great work @UnknownPlatypus .

**Comment by UnknownPlatypus** [comment]
Thank again @adamchainz for the continuous support along the way and the kind help with my first few contributions to the open source community. :pray:
