### ISSUE TITLE
`request.headers.get("Content-Length")` and `request.headers.get("Content-Type")`

### ISSUE THREAD

**Issue by christianbundy** [adamchainz/django-upgrade#224]
### Python Version

3.10

### Django Version

4.0

### Package Version

1.10

### Description

Hi! Thanks for your work on this project, I wish I'd found it sooner! I was just applying the fixers, and noticed that two HTTP headers aren't 'fixed' to user `request.headers.get()`:

- `CONTENT_LENGTH`
- `CONTENT_TYPE`

I was going to write a PR to fix this, but noticed that you have a test specifically ensuring that these are not fixed:

```python3
def test_not_header_access():
    check_noop(
        """\
        request.META['CONTENT_LENGTH']
        """,
        settings,
    )
```

Can you help me understand why these aren't fixed? I may be misunderstanding the docs:

> [`HttpRequest.headers`](https://docs.djangoproject.com/en/4.0/ref/request-response/#django.http.HttpRequest.headers)
> A case insensitive, dict-like object that provides access to all HTTP-prefixed headers (plus Content-Length and Content-Type) from the request.

Happy to help if you'd like these added to the fixer, but my gut feeling is that these were excluded intentionally and I'm misunderstanding something. Cheers.

**Comment by adamchainz** [comment]
I think I just wrote that test as an example of something in `request.META` that should not be excluded. Seems like the fixer could certainly be expanded to support them, I'd just want a test updated to something else that's in `request.META` that shouldn't be rewritten (something from WSGI?).

Sounds like you've delved into the code a bit, want to write that PR? :)

**Comment by christianbundy** [comment]
Thanks for the quick response! Yep, I'll open a PR here in a few minutes.
