### ISSUE TITLE
Django 4.2: Rename `assertFormsetError` and `assertQuerysetEqual`

### ISSUE THREAD

**Issue by icemac** [adamchainz/django-upgrade#252]
### Description

In [#33990](https://code.djangoproject.com/ticket/33990) (PR: https://github.com/django/django/pull/16110) the following test methods get renamed for Django 4.2:

* `assertFormsetError` --> `assertFormSetError`
* `assertQuerysetEqual` --> `assertQuerySetEqual`

`django-upgrade` should help to automate these changes.

**Comment by adamchainz** [comment]
Thanks for creating an isue! Yeah that seems useful, but I don't think we should add a fixer here until after it's in a release candidate, at least.

**Comment by icemac** [comment]
@adamchainz Maybe I had too much drive here on the DjangoCon Europe sprint 🏎, so I already created a PR (See #253) as suggested by @carltongibson in the Django ticket.
You might delay merging it.
