### ISSUE TITLE
Replace `ModelMultipleChoiceField`'s `list` error message with `invalid_list` 

### ISSUE THREAD

**Issue by UnknownPlatypus** [adamchainz/django-upgrade#256]
### Description

Since django 3.1, the [forms.ModelMultipleChoiceField](https://docs.djangoproject.com/en/3.1/ref/forms/fields/#modelmultiplechoicefield) `list` error message key is [deprecated](https://docs.djangoproject.com/en/3.1/releases/3.1/#id2) in favor of `invalid_list`.

SImilarly to the `EmailValidator(whitelist=...)`, I think this could be auto-fixed.

```diff
-forms.ModelMultipleChoiceField(error_messages={"list": "Enter multiple values."})
+forms.ModelMultipleChoiceField(error_messages={"invalid_list": "Enter multiple values."})
```
Would you be interested in a PR ?

**Comment by adamchainz** [comment]
Yeah sure!
