### ISSUE TITLE
How to use django-upgrade in the Pipeline?

### ISSUE THREAD

**Issue by GitRon** [adamchainz/django-upgrade#257]
### Python Version

3.10

### Django Version

4.1.1

### Package Version

1.10.0

### Description

Hi there! 

I installed your great package - thx for the update on DjangoCon! - and it works great with pre-commit. Additionally, I want to ensure via the pipeline that nobody smuggles in some deprecated code... but the best way I found was using pre-commit inside the pipeline step which feels a little off. If I run it directly, the tool will rewrite the files but not return error code 1 in case it did something.

Solution (on python-slim image):
```
    - apt-get update && apt-get install --no-install-recommends -y git
    - pip install pre-commit
    - pre-commit install -t pre-push -t pre-commit --install-hooks
    - pre-commit run --all-files --hook-stage push django-upgrade
```

Not working solution (on python-slim image):
```
    - apt-get update && apt-get install --no-install-recommends -y git
    - pip install django-upgrade
    - git ls-files -- '*.py' | xargs django-upgrade --target-version 4.1
```

Thx!

**Comment by adamchainz** [comment]
> but the best way I found was using pre-commit inside the pipeline step which feels a little off.

pre-commit recommends running `pre-commit run --all-files` in CI - [see docs](https://pre-commit.com/#usage-in-continuous-integration). The author even [created a CI service](https://pre-commit.ci/) to do that, and more.

This is the way I recommend.

But yes, the tool should exit with code 1 if it rewrites any files.

**Comment by adamchainz** [comment]
Just tested and `django-upgrade` does exit 1 when it rewrites files. And `xargs` will exit if any invocation fails. I think you maybe missed something in your test. Closing for now but if you have more info.

**Comment by GitRon** [comment]
Ok, thx for the super quick reply!
