### ISSUE TITLE
Django 4.2: Rewrite test request factory and client usage to use `headers`

### ISSUE THREAD

**Issue by David-Wobrock** [adamchainz/django-upgrade#271]
### Description

Following https://github.com/django/django/pull/16163, a new `headers` parameter was introduced in 4.2 for the 4 classes:
- `RequestFactory`
- `Client`
- `AsyncRequestFactory`
- `AsyncClient`

Let's use that parameter instead of the keyword arguments, which were prefixed with `HTTP_` for the synchronous classes (WSGI).

**Comment by adamchainz** [comment]
Basically rewrites like this:

```diff
-self.client.get("/", HTTP_USER_AGENT="curl/123", SCRIPT_NAME="/app/")
+self.client.get("/", headers={"user-agent": "curl/123"), SCRIPT_NAME="/app/")
```
