### ISSUE TITLE
Add "latest" as a target-version

### ISSUE THREAD

**Issue by ramiboutas** [adamchainz/django-upgrade#275]
### Description

I would be interested in having an additional option "latest" version of Django in the --target-version argument, so I don't have to change my pre-commit hook on every Django release. 

I don't know if that would make much sense since the code below would need probably nasty implementation :thi

```python 
    target_version: tuple[int, int] = cast(
        Tuple[int, int],
        tuple(int(x) for x in args.target_version.split(".", 1)),
    )
```

**Comment by adamchainz** [comment]
I’m not going to do that: explicit is better than implicit. I don't want a new version of django-upgrade to modify your code in unexpected ways.

Also you need to coordinate your target version of django-upgrade with your Django version - and whether you’ve yet deployed the new Django version to all your web servers, you’ve tested and don't want to roll back, etc.
