### ISSUE TITLE
NullBooleanField upgraded to BooleanField in migrations file

### ISSUE THREAD

**Issue by CLWilliam** [adamchainz/django-upgrade#283]
### Python Version

3.10

### Django Version

3.2.5 --> 4.1

### Package Version

1.11.0

### Description

While using django upgrade on the entire django project using the following in the main django project folder (powershell):
`git ls-files -- '*.py' | %{django-upgrade --target-version 4.1 $_}`

Also the migration files where targeted (one of the files before conversion, located at projects > migrations):

```python:
# Generated by Django 2.1.7 on 2020-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('projects', '0237_auto_20200420_0955'),
        ('projects', '0002_auto_20200512_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsequenceequipment',
            name='cond_data',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequenceequipment',
            name='cond_data',
            field=models.NullBooleanField(default=False),
        ),
    ]

```
As the docs says that these were not included in the NullBooleanField change & the code checks for state.looks_like_migrations_file in this fixer, this seemed like a bug to me ("migrations" is in the file path as it is the folder name)

Thanks for the package, I'm loving it!
William

**Comment by adamchainz** [comment]
`looks_like_migrations_file` is really simple:

https://github.com/adamchainz/django-upgrade/blob/main/src/django_upgrade/data.py#L64-L65

Can you try and debug why it’s not returning `True`? Seems like it could be a Windows/Powershell issue.

**Comment by CLWilliam** [comment]
Hi Adam,

it may be indeed a combining PowerShell & git ls-files issue. `git ls-files -- '*.py'` outputs the following:
```
...
projects/migrations/0001_initial.py
projects/migrations/0002_auto_20200512_1030.py
projects/migrations/0238_auto_20200424_1249.py
projects/migrations/0239_auto_20200430_1526.py
projects/migrations/0240_auto_20200505_0954.py
projects/migrations/0241_auto_20200514_1155.py
...
```
When this is passed to `looks_like_migrations_file`, this results in the following:
```
ipdb> self.filename
'projects/migrations/0238_auto_20200424_1249.py'
ipdb> os.path.sep
'\\'
ipdb> self.filename.split(os.path.sep)
['projects/migrations/0238_auto_20200424_1249.py']
```
As the separator used by git ls-files (and git bash in general) does not match the `os.path.sep`.
replacing the '/' did the trick:
```powershell:
git ls-files -- '*.py' | %{django-upgrade --target-version 4.1 $_.replace('/','\\')}
```
Is this something to be added in the docs? Or added as an argument?
An example doc change is present here:
![image](https://user-images.githubusercontent.com/34095235/199524632-19c6e0b5-d3dc-42b0-89d1-e55d4f2e4e26.png)
I've added this as [PR-285](https://github.com/adamchainz/django-upgrade/pull/285) is this seems OK for you.
Otherwise I'd gladly add it as an argument (to be used instead of os.path.sep if one is given).

**Comment by adamchainz** [comment]
Ah os.path.sep is incomplete, we need to use altsep too, if not None: https://docs.python.org/3.10/library/os.html#os.altsep

would you like to make a PR changing that instead?

**Comment by CLWilliam** [comment]
Not sure if using os.sep and os.altsep is the best way to do this:
Splitting on two delimiters can be done with re.split, the pattern will be something like:
```python:
sep_re = rf"[{os.sep}{os.altsep or ''}]"
# or to keep it simple:
sep_re = r"[\\/]"
```
Not sure if getting the path seperator from `os` would have an added value here.
But if we're already going into regex land, maybe simplifying to the general approach in data.py would be a better solution:
```python:
migrations_re = re.compile(r"(^|[\\/])migrations([\\/])")
commands_re = re.compile( r"(^|[\\/])management[\\/]commands[\\/]")
...
    @cached_property
    def looks_like_command_file(self) -> bool:
        return commands_re.search(self.filename) is not None
...
    @cached_property
    def looks_like_migrations_file(self) -> bool:
        return migrations_re.search(self.filename) is not None
...
```

also simplifying the following part as marked above:
https://github.com/adamchainz/django-upgrade/blob/06bf0b5408f38a26b6d279f39db381264004c3fb/src/django_upgrade/data.py#L55-L62

Is this ok for you?
