### ISSUE TITLE
Support more compatibility import rewrites

### ISSUE THREAD

**Issue by UnknownPlatypus** [adamchainz/django-upgrade#293]
### Description

I noticed while browsing django codebase for  `warnings.warn` that some (rather old) compatibility imports were not supported by django-upgrade.

Do you think it could be a valuable addition ?

I was thinking of using a similar pattern to anthony's [compatibility import plugin](https://github.com/asottile/pyupgrade/blob/main/pyupgrade/_plugins/imports.py) by keeping a mapping of `django-version` -> `import` (similar to the current `REWRITES` mappings) while still relying on the django-upgrade `update_import_modules` for the actual fixing. 

This could maybe lead to a small performance improvement too by grouping the existing fixer that are mostly checking the same things. As always, I'm happy to send a PR!

---
Here are the compatibility imports that I think are not currently covered.

<details>
 <summary>Imports</summary>

`--target-version 2.0`
---
- `django.utils.decorators.ContextDecorator` -> `contextlib.ContextDecorator`: Undocumented - [source](https://github.com/django/django/blob/stable/2.0.x/django/utils/decorators.py#L4)

`--target-version 1.11`
---
- `django.test.runner.setup_databases()` -> `django.test.utils.setup_databases()` : [release note](https://docs.djangoproject.com/en/4.1/releases/1.11/#tests) -  [source](https://github.com/django/django/blob/stable/1.11.x/django/test/runner.py#L688) - `RemovedInDjango21`

`--target-version 1.10`
---
- `django.contrib.staticfiles.templatetags.staticfiles.static()` -> `django.templatetags.static.static()`: [release note](https://docs.djangoproject.com/en/4.1/releases/2.1/#features-deprecated-in-2-1) - [source 1.10](https://github.com/django/django/blob/stable/1.10.x/django/contrib/staticfiles/templatetags/staticfiles.py#L9) - `RemovedInDjango30`
- `django.core.urlresolvers.*` ->  `django.urls.*`:  [release note](https://docs.djangoproject.com/en/4.1/releases/1.10/#id3) - [source](https://github.com/django/django/blob/stable/1.10.x/django/core/urlresolvers.py#L6) - `RemovedInDjango20`

`--target-version 1.9`
---
- `django.db.backends.postgresql_psycopg2.*` -> `django.db.backends.postgresql.*`: [release note](https://docs.djangoproject.com/en/4.1/releases/2.0/#id1) - [source](https://github.com/django/django/blob/stable/2.0.x/django/db/backends/postgresql_psycopg2/__init__.py#L5) - `RemovedInDjango30`.
- `django.forms.extras.SelectDateWidget` -> `django.forms.widgets.SelectDateWidget`: [release note](https://docs.djangoproject.com/en/4.1/releases/1.9/#id1) - [source](https://github.com/django/django/blob/stable/1.9.x/django/forms/extras/__init__.py#L9) - `RemovedInDjango20`

`--target-version 1.8`
---

- `django.core.context_processors.*` ->  `django.template.context_processors.*`:  [release note](https://docs.djangoproject.com/en/4.1/releases/1.8/#django-core-context-processors) - [source](https://github.com/django/django/blob/stable/1.8.x/django/core/context_processors.py) - `RemovedInDjango110`
- `django.db.models.sql.aggregates` -> `django.db.models.aggregates`:  [release note](https://docs.djangoproject.com/en/4.1/releases/1.8/#aggregate-methods-and-modules) - [source](https://github.com/django/django/blob/stable/1.8.x/django/db/models/sql/aggregates.py#L15) - `RemovedInDjango110`

`--target-version 1.6`
---
- `django.template.base.Context` -> `django.template.context.Context`: Same for `BaseContext`, `ContextPopException` and `RequestContext`:  [release note](https://docs.djangoproject.com/en/3.2/releases/3.1/#id1) - [source](https://github.com/django/django/blob/stable/1.6.x/django/template/base.py#L8) - `RemovedInDjango31`

`--target-version 1.1`
---
- `django.contrib.admin.ACTION_CHECKBOX_NAME` -> `django.contrib.admin.helpers.ACTION_CHECKBOX_NAME` : [release note]() - [source](https://github.com/django/django/blob/stable/1.1.x/django/contrib/admin/__init__.py) - `RemovedInDjango31`

</details>

**Comment by adamchainz** [comment]
Whilst most of the imports you’ve found are from pretty old versions, I think it could be valuable to group the pure import move fixers in one. I think it would be best if you could make a first PR that groups them, before we add any new ones.

Also I wouldn’t want to add any older versions than we already support (1.7), just for a few import changes.

**Comment by UnknownPlatypus** [comment]
> I think it would be best if you could make a first PR that groups them, before we add any new ones.

Makes sense, will start with the grouping then.

> Also I wouldn’t want to add any older versions than we already support (1.7), just for a few import changes.

yeah, most of them could be grouped into existing target-version maybe.
