### ISSUE TITLE
`admin.site.register` is not detected and not changed

### ISSUE THREAD

**Issue by sobolevn** [adamchainz/django-upgrade#302]
### Python Version

3.9

### Django Version

3.2

### Package Version

1.12.0

### Description

I have a file named `server/apps/identity/admin.py` with the following content:

```python
from typing import final

from django.contrib import admin

from server.apps.identity.models import User
from server.common.django.admin import TimeReadOnlyMixin


@final
class UserAdmin(TimeReadOnlyMixin, admin.ModelAdmin[User]):
    """This class represents `User` in admin panel."""

    list_display = tuple(User.REQUIRED_FIELDS)
    search_fields = (
        'email',
        'first_name',
        'last_name',
    )

admin.site.register(User)
```

If I run `django-upgrade`, nothing happens.

```
django-upgrade --target-version=3.2 server/apps/identity/admin.py
```

According to the rules specified in https://github.com/adamchainz/django-upgrade#admin-model-registration I expect `@admin.register(User)` decorator to be appended to `UserAdmin` like this:

```python
@final
@admin.register(User)
class UserAdmin(TimeReadOnlyMixin, admin.ModelAdmin[User]):
    """This class represents `User` in admin panel."""

    # ...

```

**Comment by adamchainz** [comment]
The `register()` call needs to also pass the admin class: `admin.site.register(User, UserAdmin)`. Without it, Django generates an admin class for you.
