### ISSUE TITLE
Required changes to CSRF_TRUSTED_ORIGINS

### ISSUE THREAD

**Issue by CLWilliam** [adamchainz/django-upgrade#309]
### Description

In the release notes of Django 4.0 A possible requirement is to change/add CRSF_TRUSTED_ORIGINS in the project settings.
Is this also something you want to warn users about that use Django Upgrade? Not sure if actually changing it is possible as the domains are ofcourse project specific.

https://docs.djangoproject.com/en/4.1/releases/4.0/#csrf

Kind regards,

William

**Comment by adamchainz** [comment]
I don't think this change can be automated. It's security sensitive, users need to consider which origins they trust.
