### ISSUE TITLE
admin_site.register -> @admin.register results in "undefined name 'admin_site'"

### ISSUE THREAD

**Issue by jieter** [adamchainz/django-upgrade#337]
### Python Version

3.8.13

### Django Version

4.1.7

### Package Version

1.12.0

### Description

Django-upgrade correctly transforms the `admin_site.register(StrandingSpeciesPhoto, StrandingSpeciesPhotoAdmin)` into the decorator-form`@admin.register(StrandingSpeciesPhoto, site=admin_site)`, but `admin_site` is defined after the decorator, resulting in `NameError: name 'admin_site' is not defined`.

This could be fixed by moving the definition of `admin_site` up, but I'm not sure how feasible that is. 

```diff
+ @admin.register(StrandingSpeciesPhoto, site=admin_site)
  class StrandingSpeciesPhotoAdmin(admin.ModelAdmin):
      list_display = ["__str__", "thumbnail"]
      autocomplete_fields = ["species"]
@@ -20,5 +21,4 @@ def thumbnail(self, obj):


  admin_site = StrandingAdminSite(name="stranding")
- admin_site.register(StrandingSpeciesPhoto, StrandingSpeciesPhotoAdmin)
  admin_site.register(StrandingSpecies, SpeciesAdmin)
```

**Comment by himalsofallin** [comment]
To solve this problem, you need to move the definition of admin_site up above the decorator @admin.register.

```
admin_site = StrandingAdminSite(name="stranding")

@admin.register(StrandingSpeciesPhoto, site=admin_site)
class StrandingSpeciesPhotoAdmin(admin.ModelAdmin):
    list_display = ["__str__", "thumbnail"]
    autocomplete_fields = ["species"]

admin_site.register(StrandingSpecies, SpeciesAdmin)
```

**Comment by jieter** [comment]
@himalsofallin I understand, that's how I fixed it already. 

Maybe my expectations are to high, but I expected django-upgrade fixers not to produce invalid results.

**Comment by szhorvat** [comment]
@jieter I suspect that this account is a bot. Check this out: https://github.com/igraph/rigraph/issues/710

@himalsofallin Can you give an explanation please?

**Comment by himalsofallin** [comment]
> @jieter I suspect that this account is a bot. Check this out: [igraph/rigraph#709](https://github.com/igraph/rigraph/issues/709)
> 
> @himalsofallin Can you give an explanation please?

what am i bot 🗡️  really damn bro look my profile and contributions just i wanted to help

**Comment by adamchainz** [comment]
@himalsofallin if you are using chatgpt to fill in github comments - you can do better than that. Let us hear from your authentic self.
