### ISSUE TITLE
Auto create Meta.index values for index_together usages

### ISSUE THREAD

**Issue by tim-schilling** [adamchainz/django-upgrade#344]
### Description

Django 5.1 will be removing `index_together` in favor of `Meta.indexes`. It would be useful for this tool to either update the code or provide the suggested index to be used. Ideally the new `Index` would not change the database schema. It would only change the Django migration schema.

**Comment by adamchainz** [comment]
I don't think we can “provide a suggested index”. The intention of django-upgrade is to automatically fix or do nothing, not do linting (which would be better done in a flake8 plugin).

> Ideally the new Index would not change the database schema

Afaiu adding to `Meta.indexes` will always need a migration to be generated, for the `AlterIndexTogether` and `AddIndex` operations. So this might not be such a straightforward fix, since most projects don't have a test that their migrations are up-to-date 🤔

**Comment by tim-schilling** [comment]
That's fair. I'm tossing out ideas at this point to see if any sound good.
I'm unsure if I'll have time to work on it.

What if it were a separate management command? That way we could do the
django system check for migrations.

**Comment by adamchainz** [comment]
django-upgrade isn't a django app, so it can't contain management commands or run the system checks. It's purely AST-based. I'm not sure I'd want to add a second way of installing/using it within Django.

**Comment by tim-schilling** [comment]
Well that's embarrassing on my part. Yeah, this would be more challenging for sure then. Though I believe in its "simplest" form it's:

1. Identify if a model has any `index_together` values
3. Identify if `Model.Meta.indexes` is defined, if not define it.
4. Add a corresponding `models.Index(fields=<original_tuple_or_list>)` for each element in `index_together`.

Leaving the user to run `makemigrations` to create the corresponding migration files for each of the apps.

**Comment by adamchainz** [comment]
I'm not entirely comfortable with "Leaving the user to run makemigrations to create the corresponding migration files for each of the apps." This will require a message like "changed `Meta.indexes`, run `makemigrations`", which will be liable to be missed among other fixes.

What if this feature was under a flag for one-off fixes that may require migrations? `--include-fixers-that-require-migrations` ? 😅

**Comment by MT-Cash** [comment]
https://docs.djangoproject.com/en/4.2/releases/4.2/#index-together-option-is-deprecated-in-favor-of-indexes - 4.2 already deprecated it.

**Comment by adamchainz** [comment]
Ah, the `NullBooleanField` already has the chance of making migrations. I still like the idea of putting migration-generating fixes behind an option though, as most projects indeed don’t have a test if any migrations are pending.

**Comment by adamchainz** [comment]
Thank you for sharing @caioariede, that may help with writing the first version of the rule here.

`index_together` is not supported as a single string, though, is it? https://docs.djangoproject.com/en/5.0/ref/models/options/#django.db.models.Options.index_together

**Comment by caioariede** [comment]
I think it can be either a list of strings or a list of lists containing strings
