### ISSUE TITLE
Django 5.1: Fixer for CI*Field - db_collation replacement

### ISSUE THREAD

**Issue by ulgens** [adamchainz/django-upgrade#350]
### Description

Django 4.2 deprecated `CI*Field` fields and starts to recommend using `db_collation` parameter instead. Being able to handle this with `django-upgrade` would be a nice addition.

```
* django.contrib.postgres.fields.CICharField is deprecated in favor of CharField(db_collation="…") with a case-insensitive non-deterministic collation.
* django.contrib.postgres.fields.CIEmailField is deprecated in favor of EmailField(db_collation="…") with a case-insensitive non-deterministic collation.
* django.contrib.postgres.fields.CITextField is deprecated in favor of TextField(db_collation="…") with a case-insensitive non-deterministic collation.
```
https://docs.djangoproject.com/en/4.2/releases/4.2/#id1

**Comment by adamchainz** [comment]
This one is beyond the scope of django-upgrade. You need a migration and the tool can't generate that for you.

I wrote a blog post on this change, hope that helps: https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/
