### ISSUE TITLE
does it require internet access?

### ISSUE THREAD

**Issue by brutatoasta** [adamchainz/django-upgrade#355]
### Python Version

3.9.5

### Django Version

4.2.2

### Package Version

1.13.0

### Description

does using the cli or the pre-commit hook require internet access? i am behind a firewall.

**Comment by adamchainz** [comment]
No, it doesn't.

In future, please test, rather than burden maintainers with questions that you have the power to answer.

**Comment by brutatoasta** [comment]
the pre-commit hook fetches from this repo, causing it to time out with a error 443, so it requires internet access. However, your powershell method doesn't require internet access. 

Cheers.
