### ISSUE TITLE
Django 4.1 Deprecated MemcachedCache

### ISSUE THREAD

**Issue by irtazaakram** [adamchainz/django-upgrade#366]
### Description

From https://docs.djangoproject.com/en/4.1/releases/4.1/#features-removed-in-4-1

> django.core.cache.backends.memcached.MemcachedCache will be removed.

Can we also add a fixer to replace `MemcachedCache` with either `PyMemcacheCache` or `PyLibMCCache`?

Let me know your thoughts on this. If its something that can be added I would be more than happy to contribute to it.

**Comment by adamchainz** [comment]
I don’t think this is feasible because it also requires changing which package is installed and reviewing options. Indeed that’s most of the work, changing the backend string is trivial in comparison.
