### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by q0w** [adamchainz/django-upgrade#387]
### Description

Hi, are you open to support caching like in black/mypy? Django-upgrade is running 3-5min for me.

**Comment by q0w** [comment]
I use https://github.com/suo/lintrunner to run all my linters and this adapter for django-upgrade https://github.com/justinchuby/lintrunner-adapters/blob/main/lintrunner_adapters/adapters/django_upgrade_linter.py
It runs django-upgrade on each file for diff to apply later fixes. In CI i run against all files, so it becomes pretty slow.

**Comment by adamchainz** [comment]
That tool is running one Django-upgrade process per file. That means paying the startup time for each file. It is a guaranteed slow approach for any tool, as startup time will typically be hundreds of milliseconds, whilst checking a single file will take single digit milliseconds.
