### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by sondrelg** [adamchainz/django-upgrade#4]
### Python Version

n/a

### Django Version

n/a

### Package Version

1.0.0

### Description

Hi!

Thanks for creating this!

I just had a quick question about your supported Python versions:

```yaml
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
```

Since you utilize `end_lineno`, [here](https://github.com/adamchainz/django-upgrade/blob/main/src/django_upgrade/_ast_helpers.py#L20), I _think_ you'll have troubles on Python versions earlier than 3.8, since I believe 3.8 was when `end_lineno` was added (see [this](https://restrictedpython.readthedocs.io/en/latest/contributing/changes_from37to38.html)). 

Just wanted to open this in case you were not aware of this yet - or even better, that you are aware of some backport that enables you to use `end_lineno` with earlier Python versions, that I don't know about; If that exists please let me know!

**Comment by adamchainz** [comment]
I already know this, I just released this project yesterday to PyPI to secure the name. Fixing Python 3.8 compat in #5. Will consider whether 3.6 and 3.7 support is worth it, because it makes the fixers significantly harder to write without the `end_lineno` attr.
