### ISSUE TITLE
`timezone.utc` isn't replaced when `datetime` isn't imported

### ISSUE THREAD

**Issue by browniebroke** [adamchainz/django-upgrade#409]
### Python Version

3.11

### Django Version

4.2

### Package Version

1.15.0

### Description

I have a case where `timezone.utc` isn't replaced by django-upgrade. This was introduced in #169 (requested in #135) and as far as I can tell, my use case isn't part of the tests, but I'm not sure how feasible it is:

```python
from django.utils import timezone
myfunction(date_created, tz=timezone.utc)
```

I assume it's because the value is a keyword argument? I would expect it to replace it as:

```diff
+ import datetime
+ myfunction(date_created, tz=datetime.timezone.utc)
- from django.utils import timezone
- myfunction(date_created, tz=timezone.utc)
```

Although now that I look more closely, my use case is slightly more complex, as the file also uses `timezone.now()`, in case it matters. All in all, the expected behaviour would probably be:

```diff
+ import datetime
  from django.utils import timezone

  now = timezone.now()
- myfunction(date_created, tz=timezone.utc)
+ myfunction(date_created, tz=datetime.timezone.utc)
```

**Comment by browniebroke** [comment]
Actually I found a test case which matches my use case: https://github.com/adamchainz/django-upgrade/blob/5afcc4593e7f781c0494ec87e66b2f92a6840124/tests/fixers/test_utils_timezone.py#L45-L53

I have timezone imported, but no datetime. I can see that test case was added in #227. Looks like it was intentionally decided to not handle this case, I assume there are some complications with adding a datetime import...

**Comment by UnknownPlatypus** [comment]
See https://github.com/adamchainz/django-upgrade/issues/389#issuecomment-1755656713 and related issue for a similar problem, adding import is non trivial because it could be shadowed by anything named `datetime` in scope. safely doing that imply tracking scopes and declared named I suppose

**Comment by browniebroke** [comment]
Makes sense. I see that it's actually listed as a requirement for this fixer to work in the README. Going to close this, as I don't have a good suggestion on how to implement this safely... It seems relatively unlikely that something in scope is called `datetime` without having `datetime` imported, but it's probably better to err on the safe side.

As an inspiration, we might look at libCST, which has a fixer to [add import](https://github.com/Instagram/LibCST/blob/52bbff6dfc2dd7b3086710bc64896ccfaaed1a3d/libcst/codemod/visitors/_add_imports.py#L58).

**Comment by UnknownPlatypus** [comment]
Their fixer seems to have the same issue, they don't really check scopes because it would be too expensive. See https://github.com/Instagram/LibCST/pull/1024#issuecomment-1741723160
> I agree, `AddImportsVisitor` won't be able to do a perfect job all the time unless we include expensive scope analysis into it
