### ISSUE TITLE
Rewrite `redirect(reverse(...))` calls to `redirect(...)`

### ISSUE THREAD

**Issue by UnknownPlatypus** [adamchainz/django-upgrade#410]
### Description

Hi !

I've seen the `redirect(reverse(...))` pattern quite often and it's actually redundant because de `redirect` fonction can handle [the name of a view with optional args or kwargs](https://docs.djangoproject.com/en/5.0/topics/http/shortcuts/#examples). I find this makes the code really verbose and a bit more confusing too.

That's why I think we could have a valuable autofixer here! Valid rewrite candidates would be `reverse` call without `urlconf` or `current_app` arguments (see [the `reverse` doc](https://docs.djangoproject.com/en/5.0/ref/urlresolvers/#reverse)): 
```diff
-redirect(reverse("my_app:my_view"))
+redirect("my_app:my_view")

-redirect(reverse("my_app:my_view", kwargs={"tag": "youou"}))
+redirect("my_app:my_view", kwargs={"tag": "youou"})

-redirect(reverse("arch-summary", args=[1945]))
+redirect("arch-summary", args=[1945])
```

Digging deeper in the redirect implementation, we could also fix this case (although I'm not sure it's really better, I prefer the explicit pattern):
```diff
-redirect(obj.get_absolute_url())
+redirect(obj)
```

Let me know if you would be interested in such a fixer, I'll be happy to work on it if so.

**Comment by matthiask** [comment]
```diff
-redirect(obj.get_absolute_url())
+redirect(obj)
```

Note that there's an (admittedly ugly) circumstance where this wouldn't be equivalent. If `get_absolute_url` returns a string which looks like a viewname (but cannot be reversed) this will now raise instead of redirect to `current_location + string`

```python
>>> from django.shortcuts import resolve_url
>>> resolve_url("bla")
Traceback (most recent call last):
[...]
django.urls.exceptions.NoReverseMatch: Reverse for 'bla' not found. 'bla' is not a valid view function or pattern name.
>>> resolve_url("bla/")
'bla/'
>>> 
```

**Comment by UnknownPlatypus** [comment]
hum, I think this is the other way around: 
- if `obj.get_absolute_url()` is returning "bla", `redirect(obj.get_absolute_url())` will raise 
- Otherwise,`redirect(obj)` will redirect to `current_location + 'bla'` because obj has a `get_absolute_url` method attached so `resolve_url` returns early the result of `obj.get_absolute_url()`

 But I get your point, this is not strictly equivalent in this case. And in the weird case where someone actually returns view names from  `get_absolute_url` calls, it would now raise instead.

Anyway, It confirms my initial impression that this specific case should be left as-is

**Comment by adamchainz** [comment]
I am not so hot on this proposal, it feels out of scope as it’s not an upgrade, only a redundancy removal. There are lots of patterns that could potentially be auto formatted, I don’t think we want to go down the route of “catching them all”, nor is this one particularly special or harmful.

**Comment by adamchainz** [comment]
Okay, closing now.
