### ISSUE TITLE
`request.is_ajax()` method is removed since Django 4.0.

### ISSUE THREAD

**Issue by fabiocaccamo** [adamchainz/django-upgrade#418]
### Python Version

3.12

### Django Version

5.0

### Package Version

1.15.0

### Description

Since Django 4.0 and later versions, the `is_ajax()` method has been removed.

**Comment by adamchainz** [comment]
The deprecation occurred in Django 3.1: https://docs.djangoproject.com/en/3.1/releases/3.1/#id2 . 3.1 is thus the version that django-upgrade would target, as it rewrites code on the version where the thing was deprecated.

The linked docs include the replacement, which a possible django-upgrade fixer could use.

That said, I am leaning against adding this fixer for a couple of reasons. First, Django 3.1 (and even 4.0) is several versions ago by now, so there will be fewer projects needing the upgrade. Second, I don’t think this function was ever that popular, it’s somewhat niche to switch content based upon the header from jQuery. And third, even where used, I doubt many projects would have more than a couple of usages to fix.

Thus I’m going to close this issue for now.
