### ISSUE TITLE
Convert is_authenticated() to is_authenticated

### ISSUE THREAD

**Issue by dwasyl** [adamchainz/django-upgrade#419]
### Description

Having used `django-upgrade` to bring a few applications up from `1.11`, it's been great but the upgrade scripts skipped rewriting `user.is_authenticated()` as a bool `user.is_authenticated`. Since the change was made final in Django, it should probably rewrite those references as well.

**Comment by adamchainz** [comment]
This should be possible, to detect `request.user.is_authenticated()` and remove the parentheses.

The change was made in Django 1.10: https://docs.djangoproject.com/en/1.10/releases/1.10/#using-user-is-authenticated-and-user-is-anonymous-as-methods , so that is what django-upgrade would target.
