### ISSUE TITLE
Add fixer for django.db.models.AutoField in Django 3.2

### ISSUE THREAD

**Issue by Alurith** [adamchainz/django-upgrade#429]
### Description

I was migrating a Django 2.0 to 4.2 and Django complained about `models.W042`

```shell
app.MyModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the MyAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```
Based on the [docs](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys), if a primary key is not set for each model, Django will need either this key in settings `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'` or a config  for each app.

```python
from django.apps import AppConfig

class MyAppConfig(AppConfig):
    default_auto_field = 'django.db.models.AutoField'
    name = 'my_app'
```
Do you think it's possible to add a fixer to include the `default_auto_field` in each app? 
I can work on it and make a PR.

**Comment by adamchainz** [comment]
No I don't believe this can be automatically fixed. Projects should choose which auto field they want, and sometimes on an app-by-app or model-by-model basis.
