### ISSUE TITLE
Ruff integration

### ISSUE THREAD

**Issue by inoa-jboliveira** [adamchainz/django-upgrade#450]
### Description

Hi everyone, I've been trying this project to upgrade an older project from django 2.2 to 4.2 and it is very cool! Thank you for providing this since I was wasting a lot of time reading the changelog of each version and looking for the issues.

We already use [ruff](https://github.com/astral-sh/ruff/) and it would be nice if this was integrated into their rules. Did you check if that would be possible?

**Comment by UnknownPlatypus** [comment]
See related discussion in the ruff issue tracker https://github.com/astral-sh/ruff/issues/6927

**Comment by adamchainz** [comment]
It's a separate tool and ruff has no plans to integrate per the linked issue.

**Comment by UnknownPlatypus** [comment]
@inoa-jboliveira I'll even suggest to use the [pre-commit integration](https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#pre-commit-hook), this tool is really fast, it wont be the bottleneck of you code quality pipeline. Checking a few file takes tens of milliseconds, that's it.

**Comment by inoa-jboliveira** [comment]
> @inoa-jboliveira I'll even suggest to use the [pre-commit integration](https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#pre-commit-hook), this tool is really fast, it wont be the bottleneck of you code quality pipeline. Checking a few file takes tens of milliseconds, that's it.

It is taking around 20-25s to parse our codebase as opposed to the whole ruff check taking 1.5s for around 300 rules on the same 1.5MLOC codebase. 

People here complain whenever pre-commit and pre-push start doing things that take very long. We are already at 5s pre-commit and 15s pre-push scripts and I see people using --no-verify just to go faster

**Comment by inoa-jboliveira** [comment]
Oh right, I don't need to check the whole codebase, just the changed files on pre-commit

**Comment by adamchainz** [comment]
Yeah... Rust-based tools will always be faster than Python-based ones, but Python-based ones can be edited by Python developers. I prefer that openness, to make it accessible by the Django community. There has even been talk of moving django-upgrade into the `django` GitHub organization.

I’m open to optimization PRs based on profiling, like the recent #428 which made things ~2% faster. But there’s a limit here...
