### ISSUE TITLE
Reorder Django versions in `README.rst`

### ISSUE THREAD

**Issue by smithdc1** [adamchainz/django-upgrade#460]
### Description

Hey 👋  -- Hope all is well!

The readme shows the fixes for each Django version in chronological order. 

What are your thoughts about showing them in reverse chronological order so that the most recent releases are at the top? I'm assuming that most users are looking for notes for recent versions. Avoiding the need to scroll past old versions, which will only get longer with time, would make it easier for users. 

Happy to open a PR if you think it's worthwhile.

**Comment by gav-fyi** [comment]
For what it's worth, I've considered opening an issue for the exact same thing. Would much prefer the reverse order.

**Comment by adamchainz** [comment]
Yeah this is fair, a PR reversing the order would be welcome.
