### ISSUE TITLE
Additional warning type checks. 

### ISSUE THREAD

**Issue by carltongibson** [adamchainz/django-upgrade#507]
### Description

Hey @adamchainz — not sure if this is a feature request per se... more a query... 🙂

See https://forum.djangoproject.com/t/deprecation-of-default-file-storage-can-we-easen-the-migration/34284/20

Looking at Tim's objections, I don't really disagree. There IS a certain Grrr to adding a forever warning there to Django core. (The trade-off being trying to help folks dropping off end of the deprecation period of course, so it's not _monotonic_.) 

I wonder if having a home for such in django-upgrade might fit with the scope of the package? It's not fixers per se, but _Maybe you missed this...?_ 

How does that feel to you? 

I would like to push for django-upgrade to become a featured or even official package during the next cycle. If that comes to pass  — and using django-upgrade is just part of what folks do — then such warnings _Not being in Core™_ (for whatever that means) wouldn't be such an issue. 

🤔

**Comment by adamchainz** [comment]
It feels okay. I think we could add a "linter" pass after applying fixers, and have a few built-in checks like this "old settings" one, and for other outdated constructs. For example, last year, I saw a model class with an internal `class Admin` to configure the admin, which dates back to Django <1, IIRC).

Setting file detection *is* heuristic, this being an AST-based tool, so it won't catch all the cases that a system check would. For example, for settings files without the word "settings" in their path or for alternative settings structures like django-configurations.

I would still prefer to see this in core myself, but happy to implement here instead. There's definitely an argument that folks skipping the recommended path and jumping multiple Django versions are more likely to reach for django-upgrade, so it's not such a bad home.

**Comment by carltongibson** [comment]
Thanks for the reply @adamchainz. 

>  … so it won't catch all the cases that a system check would.

That's a good point. 🤔

OK, let's just hold this as a possibility, pending the discussion around the Django PR. 

🤞

**Comment by carltongibson** [comment]
I'll close as Not Planned for now. We can always reopen if needed.
