### ISSUE TITLE
Rewrite re_path() calls into path()

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#60]
For people who did find/replace of `url()` to `re_path()`, we could help by applying the same rewriting logic of `url()` to convert `re_path()` to `path()`

This could get a little awkward with removing `re_path()` if it's no longer needed, tracking if that's needed.

**Comment by Swamii** [comment]
Thanks for the lib.
I just want to note that sometimes the view-code expects the parameter to be a `str` (not `int` for example), so automatic rewriting might cause unexpected issues for the user.
