### ISSUE TITLE
Templates - ifequal / ifnotequal

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#63]
Django 3.1 deprecated these template tags, it would be nice if we could rewrite them.

We could expand to support html files, detecting file type with [identify](https://pypi.org/project/identify/), and assuming Python by default.

For these two deprecated tags, we should be able to rewrite them with regexes. The only thing is to skip over any `verbatim` blocks. I imagine the structure will be a general splitter that feeds non-verbatim blocks into regex replacer functions. Alternatively we could use a tokenizer like django's own.

**Comment by ngnpope** [comment]
Semi-related to this, the `length_is` template filter is being deprecated in Django 4.2.

**Comment by benjaoming** [comment]
> The only thing is to skip over any verbatim blocks.

Is that super-necessary? I think that it's okay to skip: The Git diff is always there for the developer to inspect. In many cases, I imagine that the verbatim might as well be upgraded as well? People who have a file that they want to skip, might be able to skip it using the pattern in pre-commit `exclude` rule.

An approach could be to implement support for template files, and then follow up on any issues related to tokenzation of template syntax?

**Comment by adamchainz** [comment]
Yea it’s necessary and not hard to implement. We can copy Django’s tokeniser which implements the verbatim logic.

I don’t want Django-upgrade to have any false positives. It’s meant to be as reliable as pyupgrade, suitable for running on every commit. Even the most rushed/junior developer should be able to apply its changes without much inspection.

I don’t understand what you mean by “upgrade the verbatim block”, that feature hasn’t changed afaik.

**Comment by benjaoming** [comment]
Copying Django's tokenizer is probably a good trick to get the job done :+1: 

I wanted to offer a pragmatic (albeit not fully correct) path in case it made it easier to solve the issue at hand.. but it doesn't matter, discussing that aspect will take as long as the time it's intended to save :blush: I turned to the code and found that perhaps there's a bit more to solving this... I was wondering where exactly to "jump in" and fix this issue:

* I presume that solving this requires a general support for HTML files to be added somewhere, as all structures are currently designed for Python files?

* The pre-commit config anticipates that this is a "Python" hook. What might that imply? Does it affect what file paths are passed on through arguments when calling the hook? Are there other things to be aware of? See:

  https://github.com/adamchainz/django-upgrade/blob/1eb04ef266c6c4b4d282ac4840c45777f9309eb0/.pre-commit-hooks.yaml#L5-L6

  Judging from [pre-commit's docs](https://pre-commit.com/#creating-new-hooks), it would probably be cleaner to introduce a "Django-upgrade templates" hook:

  > Each git repo can support as many languages/hooks as you want.

  However, that would also require someone to add the additional template hook to their configuration. That seems annoying, although it offers a way to skip Django template fixing (for projects that use Jinja).

* Many many things are implicitly parsing Python code. What would be a good way to isolate the html-only logic (tokenizing and fixing)?

**Comment by adamchainz** [comment]
I think the most pragmatic change will be:
1. Anything that doesn't end in `.py` will be assumed to be a template. Different internal code paths, with fixers able to declare python or template fixers.
2. The default hook definition will be expanded to `types: [html, python]`, with the docs noting that perhaps you have other extensions for templates (`txt`, `xml`, ...).

**Comment by adamchainz** [comment]
Will cover this in Djade: https://github.com/adamchainz/djade/issues/23
