### ISSUE TITLE
Add support for providing folder in argument

### ISSUE THREAD

**Issue by DmytroLitvinov** [adamchainz/django-upgrade#78]
### Description

Would be nice to have a feature to provide folder as an argument.

**Comment by adamchainz** [comment]
I'm following the same policy as pyupgrade here: https://github.com/asottile/pyupgrade/issues/40#issuecomment-396057113

Use `pre-commit` or `find`+`xargs` or whatever to run the tool on all files within a directory.

**Comment by DmytroLitvinov** [comment]
Thank you for providing a response, Adam.
