### ISSUE TITLE
NullBooleanField will also fix earlier migrations

### ISSUE THREAD

**Issue by MRigal** [adamchainz/django-upgrade#79]
### Python Version

3.9.4

### Django Version

3.2.6

### Package Version

1.3.2

### Description

I wrote my code in earlier times using `NullBooleanField`, then recently I updated to 3.2 and already made the changes to the fields, also adding a new version. The code is IMHO "fixed".

Now I've added the django-upgrade check and it's trying to rewrite my earlier migrations. I guess it is not intended this way or should at least be documented.

How would you handle such a case? Some might argue that a Django version bump is a good point to reset migrations...

**Comment by adamchainz** [comment]
I did think about this, but it seems fine to to rewrite past migrations, in this case and for `JSONField`. The two definitions should give the exact same definition in the database. Did you encounter any issue, or did you just find it weird that migrations are edited?

> Some might argue that a Django version bump is a good point to reset migrations...

If by “reset” you mean “delete them then run `makemigrations`”, I am strongly against that. It’s too risky for missing some small `RunSQL` operation your code relies on. I only ever squash.

**Comment by browniebroke** [comment]
In case it helps, I avoid this problem by excluding migrations with:

```
django-upgrade --target-version 3.2 `find . -name "*.py" -type f -not -regex ".*/migrations/.*"`
```

**Comment by MRigal** [comment]
> Did you encounter any issue, or did you just find it weird that migrations are edited?

I found it weird, because it is fixed later on and feels like not respecting the history. But indeed I went through the process, tried it with data and did not encounter any issue.

> If by “reset” you mean “delete them then run makemigrations”, I am strongly against that. It’s too risky for missing some small RunSQL operation your code relies on. I only ever squash.

I've used that unprecised definition to indeed not choose between both options! But indeed, I shall rather squash them.

Thanks @browniebroke, but I am using the pre-commit hook and also running it on all files as part of my CI, so it won't apply to me.

One option might be to add the possibility to exclude migrations files (which would also make it faster, although it is fast!), but at the end, it's find for me to edit also early migrations, as django is fine with it. You may close the issue @adamchainz , and/or add a small note to the docs about it...
